eco:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    arm_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
        - shift_joint
        - lift_joint
        - finger1_joint
        - finger2_joint
        - finger3_joint
        - finger4_joint

      gains:
        shift_joint: {p: 100.0, i: 100.0, d: 100.0}
        lift_joint: {p: 50.0, i: 50.0, d: 40.0}
        finger1_joint: {p: 1.0, i: 1.0, d: 0.0}
        finger2_joint: {p: 1.0, i: 1.0, d: 0.0}
        finger3_joint: {p: 1.0, i: 1.0, d: 0.0}
        finger4_joint: {p: 1.0, i: 1.0, d: 0.0}
      stop_trajectory_duration: 0

        
